/* Abash demo — mock data (Dhaka only) */
window.ABASH_AREAS = [
  {
    name: "Mirpur",
    count: "23.9K",
    subs: [
      { name: "Mirpur 12", count: "4.1K" },
      { name: "Mirpur 10", count: "3.6K" },
      { name: "Kazipara", count: "2.8K" },
      { name: "Shah Ali", count: "1.9K" },
      { name: "Rupnagar", count: "1.4K" }
    ]
  },
  {
    name: "Uttara",
    count: "7.4K",
    subs: [
      { name: "Sector 7", count: "1.8K" },
      { name: "Sector 10", count: "2.1K" },
      { name: "Sector 13", count: "1.2K" }
    ]
  },
  {
    name: "Dhanmondi",
    count: "3.8K",
    subs: [
      { name: "Dhanmondi 27", count: "890" },
      { name: "Zigatola", count: "720" },
      { name: "Kalabagan", count: "640" }
    ]
  },
  {
    name: "Mohammadpur",
    count: "14.7K",
    subs: [
      { name: "Shekhertek", count: "2.4K" },
      { name: "Town Hall", count: "1.9K" },
      { name: "Pc Culture", count: "1.1K" }
    ]
  },
  {
    name: "Badda",
    count: "6.2K",
    subs: [
      { name: "South Badda", count: "1.7K" },
      { name: "Middle Badda", count: "1.3K" },
      { name: "Merul Badda", count: "980" }
    ]
  },
  {
    name: "Gulshan",
    count: "2.1K",
    subs: [
      { name: "Gulshan 1", count: "720" },
      { name: "Gulshan 2", count: "810" }
    ]
  }
];

window.ABASH_REVIEWS = [
  {
    quote: "Found a flat in Mirpur without calling ten brokers. Spoke to the owner the same evening.",
    quoteBn: "দশটা ব্রোকারকে না ডেকেই মিরপুরে ফ্ল্যাট পেয়েছি। ওই দিনই মালিকের সাথে কথা হয়েছে।",
    name: "Nusrat",
    nameBn: "নুসরাত",
    role: "Renter · Mirpur",
    roleBn: "ভাড়াটিয়া · মিরপুর",
    mark: "N",
    tone: "wine"
  },
  {
    quote: "Listing took a few minutes. Phone calls came from people who were actually looking.",
    quoteBn: "লিস্টিং করতে কয়েক মিনিট লেগেছে। যারা সত্যিই খুঁজছিল, তারাই ফোন করেছে।",
    name: "Rafi",
    nameBn: "রাফি",
    role: "Owner · Dhanmondi",
    roleBn: "মালিক · ধানমন্ডি",
    mark: "R",
    tone: "cream"
  },
  {
    quote: "The area filters and budget steps made it calm — not another noisy rental site.",
    quoteBn: "এলাকা আর বাজেট ধাপে ধাপে — অন্য ভাড়ার সাইটের মতো হইচই নেই।",
    name: "Sadia",
    nameBn: "সাদিয়া",
    role: "Renter · Mohammadpur",
    roleBn: "ভাড়াটিয়া · মোহাম্মদপুর",
    mark: "S",
    tone: "gold"
  },
  {
    quote: "Shared a room near campus in two days. No middleman fee, just a clear number.",
    quoteBn: "ক্যাম্পাসের কাছে রুম দুই দিনেই। মধ্যস্থতাকারীর ফি নেই — শুধু নম্বর।",
    name: "Tanvir",
    nameBn: "তানভির",
    role: "Student · Uttara",
    roleBn: "ছাত্র · উত্তরা",
    mark: "T",
    tone: "ink"
  },
  {
    quote: "Posted our PG vacancies once. Families messaged us directly — felt respectful.",
    quoteBn: "পিজি একবার পোস্ট করেই পরিবার থেকে সরাসরি মেসেজ — সম্মানজনক লাগে।",
    name: "Farhana",
    nameBn: "ফারহানা",
    role: "PG host · Banani",
    roleBn: "পিজি হোস্ট · বনানী",
    mark: "F",
    tone: "rose"
  },
  {
    quote: "Short stay for relatives — found a quiet place the afternoon before they landed.",
    quoteBn: "আত্মীয়ের শর্ট স্টে — ল্যান্ড করার আগের বিকেলেই শান্ত জায়গা পেয়েছি।",
    name: "Imran",
    nameBn: "ইমরান",
    role: "Guest · Gulshan",
    roleBn: "অতিথি · গুলশান",
    mark: "I",
    tone: "sand"
  },
  {
    quote: "Finally a rental flow that doesn’t feel like shouting into Facebook groups.",
    quoteBn: "অবশেষে এমন ভাড়া খোঁজা যা ফেসবুক গ্রুপে চিৎকারের মতো লাগে না।",
    name: "Ayesha",
    nameBn: "আয়েশা",
    role: "Renter · Bashundhara",
    roleBn: "ভাড়াটিয়া · বসুন্ধরা",
    mark: "A",
    tone: "wine"
  },
  {
    quote: "Broker-free isn’t a slogan here — the phone on the card is the landlord’s.",
    quoteBn: "ব্রোকার-ফ্রি এখানে স্লোগান নয় — কার্ডের নম্বরটাই মালিকের।",
    name: "Priya",
    nameBn: "প্রিয়া",
    role: "Renter · Lalmatia",
    roleBn: "ভাড়াটিয়া · লালমাটিয়া",
    mark: "P",
    tone: "gold"
  }
];

/** Sample listing photos (Unsplash) — demo until real upload */
window.ABASH_SAMPLE_PHOTOS = [
  "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
  "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80"
];

/** Approximate map pins (Dhaka) for demo properties */
window.ABASH_AREA_COORDS = {
  "Mirpur 12": [23.8069, 90.3683],
  Kazipara: [23.8005, 90.3738],
  "South Badda": [23.7806, 90.4266],
  Shekhertek: [23.7575, 90.3585],
  "Town Hall": [23.7655, 90.3588],
  Zigatola: [23.7392, 90.3755],
  "Dhanmondi 27": [23.7465, 90.3762],
  "Gulshan 1": [23.7808, 90.4167],
  "Sector 10": [23.8687, 90.3907],
  "Mirpur 10": [23.8035, 90.3645],
  Rupnagar: [23.8220, 90.3650],
  "Middle Badda": [23.7735, 90.4250]
};

/** Demo properties an owner attaches vacancies to (type = property class) */
window.ABASH_DEMO_BUILDINGS = [
  {
    id: "b1",
    name: "House 12, Road 3",
    type: "Home",
    area: "Mirpur",
    subArea: "Mirpur 12",
    road: "Road 3",
    block: "Block C",
    house: "House 12",
    locationNote: "Beside Popular Diagnostic, lane after the tea stall",
    lat: 23.8069,
    lng: 90.3683,
    ownerPhone: "01700000001",
    ownerName: "Kamal Hossain"
  },
  {
    id: "b2",
    name: "Green View PG",
    type: "PG",
    area: "Badda",
    subArea: "South Badda",
    road: "Progati Sarani link road",
    block: "—",
    house: "Holding 48",
    locationNote: "2 min walk from Notun Bazar foot overbridge",
    gender: "Male",
    meals: "Optional",
    lat: 23.7806,
    lng: 90.4266
  },
  {
    id: "b3",
    name: "Shekhertek Residence",
    type: "Home",
    area: "Mohammadpur",
    subArea: "Shekhertek",
    road: "Shekhertek Main Road",
    block: "—",
    house: "Plot 7",
    locationNote: "Opposite the playground, third building from the corner shop",
    lat: 23.7575,
    lng: 90.3585
  },
  {
    id: "b4",
    name: "Town Hall Girls Hostel",
    type: "Hostel",
    area: "Mohammadpur",
    subArea: "Town Hall",
    road: "Town Hall Road",
    block: "—",
    house: "Holding 19",
    locationNote: "Near university bus stop",
    gender: "Female",
    lat: 23.7655,
    lng: 90.3588
  },
  {
    id: "b5",
    name: "Gulshan 1 Office Pad",
    type: "Office",
    area: "Gulshan",
    subArea: "Gulshan 1",
    road: "Road 54",
    block: "—",
    house: "Suite building",
    locationNote: "Ground floor facing the main road",
    lat: 23.7808,
    lng: 90.4167
  },
  {
    id: "b6",
    name: "Lake View Residential Hotel",
    type: "Residential Hotel",
    area: "Dhanmondi",
    subArea: "Dhanmondi 27",
    road: "Road 27",
    block: "—",
    house: "Holding 8",
    locationNote: "Near Dhanmondi Lake, beside the cafe strip",
    lat: 23.7465,
    lng: 90.3762,
    ownerPhone: "01700000001",
    ownerName: "Kamal Hossain"
  }
];

/** Property team demo — login phone + password abash123 (OTP only on signup) */
window.ABASH_DEMO_MEMBERS = [
  {
    id: "m1",
    propertyId: "b1",
    phone: "01700000001",
    name: "Kamal Hossain",
    role: "admin"
  },
  {
    id: "m2",
    propertyId: "b1",
    phone: "01700000002",
    name: "Rashed",
    role: "editor"
  },
  {
    id: "m4",
    propertyId: "b6",
    phone: "01700000001",
    name: "Kamal Hossain",
    role: "admin"
  },
  {
    id: "m5",
    propertyId: "b6",
    phone: "01700000002",
    name: "Rashed",
    role: "editor"
  }
];

window.ABASH_DEMO_ACCOUNTS = [
  { phone: "01700000001", password: "abash123", name: "Kamal Hossain" },
  { phone: "01700000002", password: "abash123", name: "Rashed" },
  { phone: "01712345678", password: "abash123", name: "Demo Renter" }
];

window.ABASH_DEMO_TEAM_HINT =
  "Demo · Offer: 01700000001 / 01700000002 · pass abash123 · signup OTP 1234";

/** Owner listing paths — UI + vacancy fields differ by kind */
window.ABASH_KINDS = [
  {
    id: "Home",
    propertyTypes: ["Home"],
    vacancy: "unit",
    blurb: "Full flat — family or bachelor",
    blurbBn: "পুরো ফ্ল্যাট — ফ্যামিলি বা ব্যচেলর"
  },
  {
    id: "Room",
    propertyTypes: ["Home", "Room"],
    vacancy: "room",
    blurb: "Single room or sublet — not a full flat",
    blurbBn: "এক রুম বা সাবলেট — পুরো ফ্ল্যাট নয়"
  },
  {
    id: "Hostel",
    propertyTypes: ["Hostel"],
    vacancy: "seats",
    blurb: "Hostel seats — how many free",
    blurbBn: "হোস্টেল সিট — কয়টা খালি"
  },
  {
    id: "PG",
    propertyTypes: ["PG"],
    vacancy: "seats",
    blurb: "Paying Guest — monthly seat/room (not govt quarter)",
    blurbBn: "পেয়িং গেস্ট — মাসিক সিট/রুম (সরকারি কোয়ার্টার নয়)"
  },
  {
    id: "Office",
    propertyTypes: ["Office"],
    vacancy: "office",
    blurb: "Commercial floor or unit by sqft",
    blurbBn: "অফিস ফ্লোর বা ইউনিট (sqft)"
  },
  {
    id: "Short Stay",
    propertyTypes: ["Home", "Short Stay"],
    vacancy: "short",
    blurb: "Nightly stay / guest house — shared or single",
    blurbBn: "দৈনিক স্টে / গেস্ট হাউস — শেয়ার্ড বা সিঙ্গেল"
  },
  {
    id: "Residential Hotel",
    propertyTypes: ["Residential Hotel"],
    vacancy: "short",
    blurb: "আবাসিক হোটেল — nightly rooms, shared or single",
    blurbBn: "আবাসিক হোটেল — দৈনিক রুম, শেয়ার্ড বা সিঙ্গেল"
  }
];

window.ABASH_LISTINGS = [
  {
    id: "l1",
    title: "Quiet corner flat",
    titleBn: "শান্ত কোণের ফ্ল্যাট",
    category: "Home",
    buildingId: "b1",
    area: "Mirpur",
    subArea: "Mirpur 12",
    road: "Road 3",
    block: "Block C",
    house: "House 12",
    floor: "5th",
    balcony: 1,
    locationNote: "Beside Popular Diagnostic — lane after the tea stall",
    photos: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80"
    ],
    videoUrl: "https://www.youtube.com/watch?v=ScMzIvxBSi4",
    lat: 23.8069,
    lng: 90.3683,
    price: 18000,
    beds: 2,
    baths: 2,
    sqft: 950,
    media: "m1",
    phone: "01711-234567",
    owner: "Kamal Hossain",
    ownerBn: "কামাল হোসেন",
    postedDays: 2,
    availableUntil: "2026-10-31",
    description: "A calm, south-facing flat with ready gas and water lines — set back from the main road, close to everything you'd need nearby.",
    descriptionBn: "শান্ত, দক্ষিণমুখী ফ্ল্যাট — গ্যাস ও পানির লাইন প্রস্তুত। মূল সড়ক থেকে একটু ভিতরে, আশেপাশে সব সুবিধা।",
    amenities: ["Lift", "Generator", "Gas line", "Parking"],
    livingFor: "Family",
    furnished: "Furnished"
  },
  {
    id: "l2",
    title: "Sunny one-bed near Kazipara",
    titleBn: "কাজিপাড়ায় রোদময় এক বেড",
    category: "Home",
    area: "Mirpur",
    subArea: "Kazipara",
    road: "Kazipara Main Road",
    block: "—",
    house: "Holding 22",
    floor: "3rd",
    balcony: 1,
    locationNote: "Near Kazipara bus stand, left side of the pharmacy",
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.8005,
    lng: 90.3738,
    price: 11000,
    beds: 1,
    baths: 1,
    sqft: 680,
    media: "m2",
    phone: "01812-445566",
    owner: "Nusrat Jahan",
    ownerBn: "নুসরাত জাহান",
    postedDays: 1,
    availableUntil: "2026-09-30",
    description: "Compact family flat with good light, market and bus stop within walking distance.",
    descriptionBn: "কমপ্যাক্ট ফ্যামিলি ফ্ল্যাট, ভালো আলো। বাজার ও বাস স্টপ হাঁটার দূরত্বে।",
    amenities: ["Gas line", "Water line", "Balcony"],
    livingFor: "Bachelor",
    furnished: "Unfurnished"
  },
  {
    id: "l3",
    title: "Sunlit two-bed",
    titleBn: "রোদময় দুই বেড",
    category: "Home",
    area: "Mohammadpur",
    subArea: "Shekhertek",
    road: "Shekhertek Main Road",
    block: "—",
    house: "Plot 7",
    floor: "2nd",
    balcony: 2,
    locationNote: "Opposite the playground, third building from the corner shop",
    photos: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7575,
    lng: 90.3585,
    price: 15000,
    beds: 2,
    baths: 2,
    sqft: 950,
    media: "m3",
    phone: "01933-778899",
    owner: "Rafiq Ahmed",
    ownerBn: "রফিক আহমেদ",
    postedDays: 4,
    availableUntil: "2026-11-15",
    description: "Bright rooms, tiled floors, suitable for a small family. Direct owner contact.",
    descriptionBn: "উজ্জ্বল রুম, টাইলস ফ্লোর — ছোট পরিবারের জন্য উপযুক্ত। সরাসরি মালিকের সাথে যোগাযোগ।",
    amenities: ["Lift", "Generator", "Parking"],
    livingFor: "Family",
    furnished: "Semi"
  },
  {
    id: "l4",
    title: "Garden-view family flat",
    titleBn: "গার্ডেন ভিউ ফ্যামিলি ফ্ল্যাট",
    category: "Home",
    area: "Dhanmondi",
    subArea: "Zigatola",
    road: "Zigatola Road",
    block: "—",
    house: "House 41/A",
    floor: "6th",
    balcony: 2,
    locationNote: "Behind the old market, next to the book binding shop",
    photos: [
      "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7392,
    lng: 90.3755,
    price: 27000,
    beds: 3,
    baths: 2,
    sqft: 1400,
    media: "m4",
    phone: "01670-112233",
    owner: "Sadia Rahman",
    ownerBn: "সাদিয়া রহমান",
    postedDays: 3,
    availableUntil: "2026-12-01",
    description: "Spacious three-bed overlooking a quiet lane. Ideal for families relocating to Dhanmondi.",
    descriptionBn: "শান্ত গলির দিকে তিন বেডের প্রশস্ত ফ্ল্যাট। ধানমন্ডিতে স্থানান্তরের জন্য উপযোগী।",
    amenities: ["Lift", "Generator", "Gas line", "Parking", "CCTV"],
    livingFor: "Family",
    furnished: "Furnished"
  },
  {
    id: "l5",
    title: "Bachelor room with attached bath",
    titleBn: "অ্যাটাচড বাথসহ ব্যচেলর রুম",
    category: "Room",
    area: "Mirpur",
    subArea: "Mirpur 10",
    photos: [
      "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.8035,
    lng: 90.3645,
    price: 7000,
    beds: 1,
    baths: 1,
    sqft: 180,
    media: "m5",
    phone: "01521-998877",
    owner: "Imran Kabir",
    ownerBn: "ইমরান কবির",
    postedDays: 0,
    availableUntil: "2026-09-20",
    description: "Single room for bachelor, attached bath, shared kitchen. Wi‑Fi available.",
    descriptionBn: "ব্যচেলরের জন্য সিঙ্গেল রুম, অ্যাটাচড বাথ, শেয়ার্ড কিচেন। ওয়াই‑ফাই আছে।",
    amenities: ["Wi‑Fi", "Attached bath", "Shared kitchen"],
    attachedBath: true,
    kitchen: "Shared",
    stayType: "Single",
    furnished: "Furnished"
  },
  {
    id: "l6",
    title: "Girls hostel seat",
    titleBn: "গার্লস হোস্টেল সিট",
    category: "Hostel",
    area: "Mohammadpur",
    subArea: "Town Hall",
    photos: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7655,
    lng: 90.3588,
    price: 5500,
    beds: 1,
    baths: 1,
    sqft: 120,
    media: "m6",
    phone: "01799-554433",
    owner: "Farzana Akter",
    ownerBn: "ফারজানা আক্তার",
    postedDays: 5,
    availableUntil: "2026-10-10",
    description: "Secure girls hostel, meals optional, close to university bus routes.",
    descriptionBn: "নিরাপদ গার্লস হোস্টেল, খাবার ঐচ্ছিক। বিশ্ববিদ্যালয় বাস রুটের কাছে।",
    amenities: ["Security", "Wi‑Fi", "Meals optional"],
    gender: "Female",
    seatsFree: 2,
    roomType: "Shared room",
    stayType: "Shared"
  },
  {
    id: "l7",
    title: "PG for working professionals",
    titleBn: "কর্মজীবীদের জন্য পিজি",
    category: "PG",
    area: "Badda",
    subArea: "South Badda",
    photos: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7806,
    lng: 90.4266,
    price: 9000,
    beds: 1,
    baths: 1,
    sqft: 200,
    media: "m1",
    phone: "01888-223344",
    owner: "Tanvir Hasan",
    ownerBn: "তানভীর হাসান",
    postedDays: 2,
    availableUntil: "2026-09-28",
    description: "Paying guest setup with AC option, housekeeper twice a week.",
    descriptionBn: "পিজি সেটআপ, এসি অপশন, সপ্তাহে দুবার গৃহকর্মী।",
    amenities: ["AC option", "Housekeeping", "Wi‑Fi"],
    gender: "Male",
    seatsFree: 1,
    roomType: "Private room",
    stayType: "Single"
  },
  {
    id: "l8",
    title: "Small office space",
    titleBn: "ছোট অফিস স্পেস",
    category: "Office",
    area: "Gulshan",
    subArea: "Gulshan 1",
    photos: [
      "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7808,
    lng: 90.4167,
    price: 45000,
    beds: 0,
    baths: 1,
    sqft: 800,
    media: "m5",
    phone: "01911-667788",
    owner: "Ayesha Karim",
    ownerBn: "আয়েশা করিম",
    postedDays: 6,
    availableUntil: "2026-11-30",
    description: "Ground-floor office with reception area, suitable for a 6–8 person team.",
    descriptionBn: "গ্রাউন্ড ফ্লোর অফিস, রিসেপশন এরিয়া — ৬–৮ জনের টিমের জন্য উপযুক্ত।",
    amenities: ["Reception", "Parking", "Generator", "CCTV"]
  },
  {
    id: "l9",
    title: "Short stay studio",
    titleBn: "শর্ট স্টে স্টুডিও",
    category: "Short Stay",
    area: "Dhanmondi",
    subArea: "Dhanmondi 27",
    price: 2500,
    beds: 1,
    baths: 1,
    sqft: 350,
    media: "m2",
    phone: "01611-334455",
    owner: "Mehedi Islam",
    ownerBn: "মেহেদী ইসলাম",
    postedDays: 1,
    availableUntil: "2026-09-15",
    description: "Daily rate studio for short stays. Price shown is per night.",
    descriptionBn: "শর্ট স্টের জন্য ডেইলি রেট স্টুডিও। দেখানো দাম প্রতি রাতের।",
    amenities: ["Wi‑Fi", "AC", "Kitchenette", "Single"],
    priceUnit: "night",
    stayType: "Single",
    photos: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80"
    ],
    videoUrl: "https://www.youtube.com/watch?v=ScMzIvxBSi4",
    lat: 23.7465,
    lng: 90.3762
  },
  {
    id: "l10",
    title: "Family flat near Sector 10",
    titleBn: "সেক্টর ১০ এর কাছে ফ্যামিলি ফ্ল্যাট",
    category: "Home",
    area: "Uttara",
    subArea: "Sector 10",
    photos: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.8687,
    lng: 90.3907,
    price: 22000,
    beds: 3,
    baths: 2,
    sqft: 1250,
    media: "m3",
    phone: "01755-889900",
    owner: "Shafiqul Islam",
    ownerBn: "শফিকুল ইসলাম",
    postedDays: 3,
    availableUntil: "2026-10-20",
    description: "Well-kept flat close to lakeside parks and schools.",
    descriptionBn: "লেকসাইড পার্ক ও স্কুলের কাছে ভালো রাখা ফ্ল্যাট।",
    amenities: ["Lift", "Generator", "Parking", "Gas line"],
    livingFor: "Family",
    furnished: "Semi"
  },
  {
    id: "l11",
    title: "Rupnagar 2 bed",
    titleBn: "রূপনগর দুই বেড",
    category: "Home",
    area: "Mirpur",
    subArea: "Rupnagar",
    photos: [
      "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.822,
    lng: 90.365,
    price: 14000,
    beds: 2,
    baths: 1,
    sqft: 850,
    media: "m4",
    phone: "01820-556677",
    owner: "Habib Ullah",
    ownerBn: "হাবিব উল্লাহ",
    postedDays: 7,
    availableUntil: "2026-09-25",
    description: "Affordable two-bed in a quiet residential block.",
    descriptionBn: "শান্ত আবাসিক ব্লকে সাশ্রয়ী দুই বেড।",
    amenities: ["Gas line", "Balcony"],
    livingFor: "Family",
    furnished: "Unfurnished"
  },
  {
    id: "l12",
    title: "Middle Badda sublet room",
    titleBn: "মিডল বাড্ডা সাবলেট রুম",
    category: "Room",
    area: "Badda",
    subArea: "Middle Badda",
    photos: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7735,
    lng: 90.425,
    price: 8000,
    beds: 1,
    baths: 1,
    sqft: 160,
    media: "m6",
    phone: "01960-112211",
    owner: "Lisa Chowdhury",
    ownerBn: "লিসা চৌধুরী",
    postedDays: 2,
    availableUntil: "2026-09-18",
    description: "Furnished room available for sublet until year end.",
    descriptionBn: "বছর শেষ পর্যন্ত সাবলেটের জন্য সাজানো রুম।",
    amenities: ["Furnished", "Wi‑Fi", "Shared kitchen"],
    attachedBath: false,
    kitchen: "Shared",
    stayType: "Shared",
    furnished: "Furnished"
  },
  {
    id: "l13",
    title: "Lake View hotel room",
    titleBn: "লেক ভিউ হোটেল রুম",
    category: "Residential Hotel",
    buildingId: "b6",
    area: "Dhanmondi",
    subArea: "Dhanmondi 27",
    road: "Road 27",
    house: "Holding 8",
    locationNote: "Near Dhanmondi Lake, beside the cafe strip",
    price: 3200,
    priceUnit: "night",
    beds: 1,
    baths: 1,
    stayType: "Single",
    attachedBath: true,
    kitchen: "None",
    media: "m10",
    photos: [
      "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80"
    ],
    videoUrl: "https://www.youtube.com/watch?v=ScMzIvxBSi4",
    lat: 23.7465,
    lng: 90.3762,
    phone: "01740-556677",
    owner: "Lake View RH",
    ownerBn: "লেক ভিউ আরএইচ",
    postedDays: 1,
    availableUntil: "2026-12-31",
    description: "Clean single room in a residential hotel — AC, attached bath, daily housekeeping. Not a full Airbnb booking flow — call to reserve.",
    descriptionBn: "আবাসিক হোটেলে পরিষ্কার সিঙ্গেল রুম — এসি, অ্যাটাচড বাথ। কল করে রিজার্ভ করুন।",
    amenities: ["AC", "Attached bath", "Housekeeping", "Single"]
  },
  {
    id: "l14",
    title: "Shared twin room — residential hotel",
    titleBn: "শেয়ার্ড টুইন রুম — আবাসিক হোটেল",
    category: "Residential Hotel",
    buildingId: "b6",
    area: "Dhanmondi",
    subArea: "Dhanmondi 27",
    price: 1800,
    priceUnit: "night",
    beds: 2,
    baths: 1,
    stayType: "Shared",
    attachedBath: false,
    kitchen: "Shared",
    photos: [
      "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80"
    ],
    lat: 23.7468,
    lng: 90.3765,
    phone: "01740-556677",
    owner: "Lake View RH",
    ownerBn: "লেক ভিউ আরএইচ",
    postedDays: 0,
    availableUntil: "2026-12-31",
    description: "Shared twin room — budget nightly stay near the lake.",
    descriptionBn: "শেয়ার্ড টুইন রুম — লেকের কাছে সাশ্রয়ী দৈনিক স্টে।",
    amenities: ["Shared room", "Shared bath", "Wi‑Fi"]
  }
];

window.ABASH_I18N = {
  en: {
    demoBanner: "Client demo · mock data · no real SMS/payments",
    explore: "Explore",
    listPlace: "Offer a place",
    wishlist: "Saved",
    dashboard: "Dashboard",
    signIn: "Sign in",
    signOut: "Sign out",
    lang: "বাংলা",
    heroTitle: "Find a place that feels right.",
    heroSub: "Homes, rooms, hostels, and more — broker-free across Dhaka.",
    quickPath: "Quick path",
    howSearch: "Search",
    howFilter: "Filter",
    howCall: "Call",
    searchCta: "Search places",
    lookingFor: "Looking for",
    budget: "Budget",
    bedrooms: "Bedrooms",
    area: "Area",
    searchPlaces: "Search places",
    homeNote: "Photos appear after you search — the homepage stays calm and focused.",
    whyKicker: "Why Abash",
    whyBroker: "Broker-free",
    whyDirect: "Direct number",
    whyCalm: "Calm search",
    whyMore: "More about us",
    offerBandKicker: "For owners & hosts",
    offerBandTitle: "Place empty? List it on Abash.",
    offerBandSub: "Homes, rooms, hostels, PG — people looking find you directly.",
    pulseActive: "active offers",
    pulseMirpur: "Mirpur — 12 new today",
    pulseDhan: "Dhanmondi — 3 rooms just listed",
    pulseBroker: "Broker-free across Dhaka",
    pulseUttara: "Uttara — hostel beds open",
    pulseBanani: "people searching Banani now",
    selectArea: "Select area",
    searchArea: "Search area or sub-area…",
    recent: "Recently searched",
    dhakaAreas: "Dhaka areas",
    placesFound: "places found",
    refine: "Refine",
    refineApply: "Show places",
    reviewsKicker: "From people on Abash",
    reviewsTitle: "Quiet finds, honest words",
    reviewsHint: "Color cards in a slow river — hover to pause.",
    whyPageTitle: "Why Abash",
    whyPageBody: "Full story coming soon — the home teaser already links here.",
    whyPageBack: "Back to home",
    floor: "Floor",
    balcony: "Balcony",
    location: "Location",
    building: "Property",
    addBuilding: "+ Add property",
    editProperty: "Edit",
    saveProperty: "Save property",
    livingFor: "Living for",
    family: "Family",
    bachelor: "Bachelor",
    furnishLabel: "Furnishing",
    furnished: "Furnished",
    semiFurnished: "Semi",
    unfurnished: "Unfurnished",
    attachedBath: "Attached bath",
    sharedBath: "Shared bath",
    kitchen: "Kitchen",
    noKitchen: "No kitchen",
    sharedKitchen: "Shared kitchen",
    privateKitchen: "Private kitchen",
    road: "Road",
    block: "Block",
    house: "House / holding",
    locationHint: "Landmark / how to find",
    unitDetails: "Unit details",
    viewAll: "View all",
    save: "Save",
    saved: "Saved",
    callOwner: "Call",
    report: "Report this listing",
    thePlace: "The place",
    amenities: "Amenities",
    owner: "Posted by",
    availableUntil: "Available until",
    perMonth: "/ month",
    perNight: "/ night",
    emptyTitle: "Nothing here yet",
    emptySub: "Try another area or loosen filters.",
    loginTitle: "Sign in",
    signupTitle: "Create account",
    phone: "Phone",
    password: "Password",
    passwordConfirm: "Confirm password",
    otp: "OTP code",
    sendOtp: "Send OTP",
    verifyContinue: "Verify & continue",
    signInBtn: "Sign in",
    asRenter: "Looking",
    asOwner: "Offer a place",
    name: "Your name",
    noAccount: "New here?",
    hasAccount: "Have an account?",
    createAccount: "Create account",
    wishlistTitle: "Saved places",
    wishlistEmpty: "Nothing saved yet. Tap the heart on a listing.",
    listTitle: "Offer a place",
    listSub: "Choose what you’re offering — the form follows that.",
    listStepKind: "1 · What are you offering?",
    listStepProperty: "2 · Which property?",
    listStepVacancy: "3 · What’s vacant?",
    continue: "Continue",
    back: "Back",
    seatsFree: "Seats free",
    roomType: "Room type",
    publish: "Publish",
    noPropertyYet: "No matching property — search or add one below.",
    propertySaved: "Property saved",
    propertyUpdated: "Property updated",
    pickProperty: "Offering",
    pickPropertyHint: "— search an existing property, or create one.",
    searchProperty: "Search property name or area…",
    mapLabel: "Map location",
    openMaps: "Open in Google Maps",
    photosLabel: "Photos",
    videoLabel: "Video tour (YouTube link)",
    pickPhotos: "Pick demo photos",
    stayType: "Room style",
    staySingle: "Single",
    stayShared: "Shared",
    mapHint: "Pin shown on listing map",
    dashTitle: "Dashboard",
    myListings: "My offers",
    views: "Views",
    active: "Active",
    renew: "Renew",
    edit: "Edit",
    remove: "Remove",
    teamDemoShort: "demo accounts in Sign in",
    staffOnly: "Sign in to offer a place",
    teamRoleHint: "Access",
    yourRole: "Role",
    manageTeam: "Editors",
    addEditor: "Add editor",
    orgSetup: "Property access (admin → editor)",
    orgSetupHint: "Invite by phone. They use phone + password — not shown publicly on offers.",
    scrollCats: "← scroll for more (Hotel is here too) →",
    cannotAddProperty: "Only a property admin can add or edit building info.",
    cannotPublish: "You can’t publish on this property",
    cannotPublishHint: "Ask the property admin to add you as an editor.",
    cannotManageTeam: "Only the property admin can manage editors",
    propertyTeam: "Property editors",
    propertyTeamSub: "Invite by phone. They sign in with phone + password — roles stay private.",
    teamMembers: "People with access",
    inviteMember: "Invite editor",
    teamRole: "Role",
    roleOwner: "Admin",
    roleManager: "Editor",
    roleCaretaker: "Editor",
    roleAdmin: "Admin",
    roleEditor: "Editor",
    inviteHint: "They use this phone + their password. No public “manager” label on listings.",
    sendInvite: "Save invite",
    inviteSaved: "Editor invite saved",
    memberRemoved: "Removed",
    noTeamInvite: "No property access for this phone yet",
    publicContact: "Contact phone (on the offer)",
    publicContactHint: "Renters call this number — shown on the offer only",
    contactPerson: "Contact",
    publicPhone: "Phone",
    markRented: "Mark rented",
    markVacant: "Mark vacant again",
    rented: "Rented",
    dashEmptyHint: "Publish an offer, or get invited as an editor on a property.",
    profileTitle: "Offers from",
    profileReviewsLater: "Reviews coming later",
    moreOffers: "More offers",
    authHintSignup: "We’ll send a one-time OTP, then you use phone + password next time.",
    authHintLogin: "Phone + password. New? Create an account (OTP once).",
    wrongPassword: "Wrong phone or password",
    passwordShort: "Password at least 6 characters",
    passwordMismatch: "Passwords don’t match",
    accountExists: "Account exists — sign in",
    needAccount: "Create an account first",
    any: "Any",
    under10: "Under ৳10k",
    b10_20: "৳10k – 20k",
    b20_30: "৳20k – 30k",
    b30: "৳30k+",
    oUnder30: "Under ৳30k",
    o30_50: "৳30k – 50k",
    o50_80: "৳50k – 80k",
    o80: "৳80k+",
    nUnder2: "Under ৳2k/night",
    n2_4: "৳2k – 4k/night",
    n4_6: "৳4k – 6k/night",
    n6: "৳6k+/night",
    bathFilter: "Bathroom",
    genderFilter: "For",
    genderFemale: "Female",
    genderMale: "Male",
    sizeFilter: "Min size",
    tapArea: "Tap to choose area or sub-area",
    sortNewest: "Newest",
    sortPriceAsc: "Price ↑",
    sortPriceDesc: "Price ↓",
    proofListings: "listings",
    proofToday: "added today",
    proofBroker: "no broker fee",
    proofDhaka: "Dhaka only"
  },
  bn: {
    demoBanner: "ক্লায়েন্ট ডেমো · মক ডেটা · আসল SMS/পেমেন্ট নেই",
    explore: "খুঁজুন",
    listPlace: "জায়গা দিন",
    wishlist: "সেভ",
    dashboard: "ড্যাশবোর্ড",
    signIn: "লগ ইন",
    signOut: "লগ আউট",
    lang: "EN",
    heroTitle: "এমন একটা জায়গা খুঁজুন যা মনে ধরে।",
    heroSub: "বাসা, রুম, হোস্টেলসহ আরও — ঢাকায় ব্রোকার ছাড়াই।",
    quickPath: "সহজ পথ",
    howSearch: "খুঁজুন",
    howFilter: "ফিল্টার",
    howCall: "কল",
    searchCta: "জায়গা খুঁজুন",
    lookingFor: "কী চাইছেন",
    budget: "বাজেট",
    bedrooms: "বেডরুম",
    area: "এলাকা",
    searchPlaces: "খুঁজুন",
    homeNote: "সার্চ করার পরই ছবি দেখা যাবে — হোমপেজ শান্ত ও ফোকাসড থাকে।",
    whyKicker: "কেন Abash",
    whyBroker: "ব্রোকার-ফ্রি",
    whyDirect: "সরাসরি নম্বর",
    whyCalm: "শান্ত সার্চ",
    whyMore: "আরও জানুন",
    offerBandKicker: "মালিক ও হোস্টদের জন্য",
    offerBandTitle: "জায়গা খালি? Abash-এ লিস্ট করুন।",
    offerBandSub: "বাসা, রুম, হোস্টেল, পিজি — খোঁজা মানুষ সরাসরি পাবেন।",
    pulseActive: "সক্রিয় অফার",
    pulseMirpur: "মিরপুর — আজ ১২টা নতুন",
    pulseDhan: "ধানমন্ডি — ৩টা রুম এইমাত্র",
    pulseBroker: "ঢাকাজুড়ে ব্রোকার-ফ্রি",
    pulseUttara: "উত্তরা — হোস্টেল বেড খোলা",
    pulseBanani: "জন এখন বনানী খুঁজছেন",
    selectArea: "এলাকা বাছুন",
    searchArea: "এলাকা বা সাব‑এরিয়া খুঁজুন…",
    recent: "সম্প্রতি খোঁজা",
    dhakaAreas: "ঢাকার এলাকা",
    placesFound: "টি জায়গা পাওয়া গেছে",
    refine: "ফিল্টার",
    refineApply: "দেখান",
    reviewsKicker: "Abash ব্যবহারকারীদের কথা",
    reviewsTitle: "শান্ত খোঁজ, সৎ মতামত",
    reviewsHint: "কালার কার্ড ধীরে বয়ে যায় — থামাতে হোভার করুন।",
    whyPageTitle: "কেন Abash",
    whyPageBody: "পুরো গল্প শিগগির — হোমের টিজার এখানেই লিঙ্ক করে।",
    whyPageBack: "হোমে ফিরুন",
    floor: "তলা",
    balcony: "বারান্দা",
    location: "ঠিকানা",
    building: "প্রপার্টি",
    addBuilding: "+ প্রপার্টি যোগ",
    editProperty: "এডিট",
    saveProperty: "প্রপার্টি সেভ",
    livingFor: "কার জন্য",
    family: "ফ্যামিলি",
    bachelor: "ব্যচেলর",
    furnishLabel: "ফার্নিশিং",
    furnished: "ফার্নিশড",
    semiFurnished: "সেমি",
    unfurnished: "আনফার্নিশড",
    attachedBath: "অ্যাটাচড বাথ",
    sharedBath: "শেয়ার্ড বাথ",
    kitchen: "কিচেন",
    noKitchen: "কিচেন নেই",
    sharedKitchen: "শেয়ার্ড কিচেন",
    privateKitchen: "প্রাইভেট কিচেন",
    road: "রোড",
    block: "ব্লক",
    house: "বাড়ি / হোল্ডিং",
    locationHint: "ল্যান্ডমার্ক / খুঁজে পাওয়ার উপায়",
    unitDetails: "ইউনিটের বিবরণ",
    viewAll: "সব দেখুন",
    save: "সেভ",
    saved: "সেভড",
    callOwner: "কল করুন",
    report: "এই লিস্টিং রিপোর্ট করুন",
    amenities: "সুবিধা",
    thePlace: "জায়গাটি",
    owner: "পোস্ট করেছেন",
    availableUntil: "উপলব্ধ",
    perMonth: "/ মাস",
    perNight: "/ রাত",
    emptyTitle: "কোনো মিল নেই",
    emptySub: "অন্য এলাকা, বাজেট বা ক্যাটাগরি চেষ্টা করুন।",
    loginTitle: "সাইন ইন",
    signupTitle: "অ্যাকাউন্ট তৈরি",
    phone: "মোবাইল নম্বর",
    password: "পাসওয়ার্ড",
    passwordConfirm: "পাসওয়ার্ড আবার",
    otp: "OTP কোড",
    sendOtp: "OTP পাঠান",
    verifyContinue: "ভেরিফাই করে এগোন",
    signInBtn: "সাইন ইন",
    asRenter: "খুঁজছি",
    asOwner: "জায়গা দিন",
    name: "আপনার নাম",
    noAccount: "নতুন?",
    hasAccount: "অ্যাকাউন্ট আছে?",
    createAccount: "অ্যাকাউন্ট তৈরি",
    wishlistTitle: "সেভ করা জায়গা",
    wishlistEmpty: "এখনো কিছু সেভ নেই। লিস্টিংয়ে হার্ট চাপুন।",
    listTitle: "জায়গা দিন",
    listSub: "কী দিচ্ছেন বেছে নিন — ফর্ম সেই অনুযায়ী বদলাবে।",
    listStepKind: "১ · কী দিচ্ছেন?",
    listStepProperty: "২ · কোন প্রপার্টি?",
    listStepVacancy: "৩ · কী খালি?",
    continue: "এগোন",
    back: "পেছনে",
    seatsFree: "খালি সিট",
    roomType: "রুমের ধরন",
    publish: "প্রকাশ করুন",
    noPropertyYet: "মিল নেই — সার্চ করুন বা নিচে নতুন যোগ করুন।",
    propertySaved: "প্রপার্টি সেভ হয়েছে",
    propertyUpdated: "প্রপার্টি আপডেট হয়েছে",
    pickProperty: "অফার",
    pickPropertyHint: "— আগের প্রপার্টি খুঁজুন, না থাকলে তৈরি করুন।",
    searchProperty: "প্রপার্টির নাম বা এলাকা খুঁজুন…",
    mapLabel: "ম্যাপ লোকেশন",
    openMaps: "Google Maps এ খুলুন",
    photosLabel: "ছবি",
    videoLabel: "ভিডিও ট্যুর (YouTube link)",
    pickPhotos: "ডেমো ছবি বাছুন",
    stayType: "রুমের স্টাইল",
    staySingle: "সিঙ্গেল",
    stayShared: "শেয়ার্ড",
    mapHint: "লিস্টিং ম্যাপে পিন দেখাবে",
    dashTitle: "ড্যাশবোর্ড",
    myListings: "আমার অফার",
    views: "ভিউ",
    active: "সক্রিয়",
    renew: "নবায়ন",
    edit: "সম্পাদনা",
    remove: "মুছুন",
    teamDemoShort: "সাইন ইনে ডেমো অ্যাকাউন্ট",
    staffOnly: "জায়গা দিতে সাইন ইন করুন",
    teamRoleHint: "অ্যাক্সেস",
    yourRole: "রোল",
    manageTeam: "এডিটর",
    addEditor: "এডিটর যোগ",
    orgSetup: "প্রপার্টি অ্যাক্সেস (admin → editor)",
    orgSetupHint: "ফোন দিয়ে ইনভাইট। তারা ফোন+পাসওয়ার্ডে লগইন — অফারে পাবলিক নয়।",
    scrollCats: "← স্ক্রল করুন (Hotel এখানেই) →",
    cannotAddProperty: "বিল্ডিং ইনফো শুধু প্রপার্টি অ্যাডমিন বদলাতে পারে।",
    cannotPublish: "এই প্রপার্টিতে পাবলিশ করতে পারবেন না",
    cannotPublishHint: "প্রপার্টি অ্যাডমিনকে এডিটর হিসেবে যোগ করতে বলুন।",
    cannotManageTeam: "শুধু অ্যাডমিন এডিটর ম্যানেজ করতে পারে",
    propertyTeam: "প্রপার্টি এডিটর",
    propertyTeamSub: "ফোন দিয়ে ইনভাইট। ফোন+পাসওয়ার্ডে লগইন — পাবলিকে ম্যানেজার লেবেল নেই।",
    teamMembers: "যাদের অ্যাক্সেস আছে",
    inviteMember: "এডিটর ইনভাইট",
    teamRole: "রোল",
    roleOwner: "অ্যাডমিন",
    roleManager: "এডিটর",
    roleCaretaker: "এডিটর",
    roleAdmin: "অ্যাডমিন",
    roleEditor: "এডিটর",
    inviteHint: "এই ফোন + তাদের পাসওয়ার্ড।",
    sendInvite: "ইনভাইট সেভ",
    inviteSaved: "এডিটর ইনভাইট সেভ",
    memberRemoved: "সরানো হয়েছে",
    noTeamInvite: "এই ফোনে এখনো প্রপার্টি অ্যাক্সেস নেই",
    publicContact: "কন্টাক্ট ফোন (অফারে)",
    publicContactHint: "ভাড়াটিয়া এই নম্বরে কল করবে",
    contactPerson: "যোগাযোগ",
    publicPhone: "ফোন",
    markRented: "ভাড়া হয়েছে",
    markVacant: "আবার খালি",
    rented: "ভাড়া হয়েছে",
    dashEmptyHint: "অফার প্রকাশ করুন, অথবা এডিটর ইনভাইট নিন।",
    profileTitle: "অফার —",
    profileReviewsLater: "রিভিউ পরে আসবে",
    moreOffers: "আরও অফার",
    authHintSignup: "একবার OTP, তারপর ফোন + পাসওয়ার্ড।",
    authHintLogin: "ফোন + পাসওয়ার্ড। নতুন? অ্যাকাউন্ট তৈরি (OTP একবার)।",
    wrongPassword: "ফোন বা পাসওয়ার্ড ভুল",
    passwordShort: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষর",
    passwordMismatch: "পাসওয়ার্ড মিলছে না",
    accountExists: "অ্যাকাউন্ট আছে — সাইন ইন করুন",
    needAccount: "আগে অ্যাকাউন্ট তৈরি করুন",
    any: "যেকোনো",
    under10: "৳১০ হাজারের কম",
    b10_20: "৳১০–২০ হাজার",
    b20_30: "৳২০–৩০ হাজার",
    b30: "৳৩০ হাজার+",
    oUnder30: "৳৩০ হাজারের কম",
    o30_50: "৳৩০–৫০ হাজার",
    o50_80: "৳৫০–৮০ হাজার",
    o80: "৳৮০ হাজার+",
    nUnder2: "রাত ৳২ হাজারের কম",
    n2_4: "রাত ৳২–৪ হাজার",
    n4_6: "রাত ৳৪–৬ হাজার",
    n6: "রাত ৳৬ হাজার+",
    bathFilter: "বাথরুম",
    genderFilter: "কার জন্য",
    genderFemale: "নারী",
    genderMale: "পুরুষ",
    sizeFilter: "মিনিমাম সাইজ",
    tapArea: "এলাকা বা সাব‑এরিয়া বাছতে ট্যাপ করুন",
    sortNewest: "নতুন",
    sortPriceAsc: "দাম ↑",
    sortPriceDesc: "দাম ↓",
    proofListings: "লিস্টিং",
    proofToday: "আজ যোগ",
    proofBroker: "ব্রোকার ফি নেই",
    proofDhaka: "শুধু ঢাকা"
  }
};
